#pragma once

typedef enum MDLRS_Interpolation MDLRS_Interpolation;
enum MDLRS_Interpolation
{
	INTERPOLATION_NONE,
	INTERPOLATION_LINEAR,
	INTERPOLATION_FAST,
	INTERPOLATION_SLOW,
	INTERPOLATION_SMOOTH
};